name: Compile Arduino sketch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Compile the sketch for Arduino Pro Mini
        working-directory: ./arduino
        run: |
          cmake -B build-pro -DPROFILE=pro
          cmake --build build-pro

      - name: Upload build-pro - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }}-${{ env.repository_name }}-pro.avr.hex
          path: arduino/build-pro/aop-pro.avr.hex

      - name: Compile the sketch for ESP32 C3
        working-directory: ./arduino
        run: |
          cmake -B build-c3 -DPROFILE=c3
          cmake --build build-c3

      - name: Upload build-c3 - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }}-${{ env.repository_name }}-c3.esp32.bin
          path: arduino/build-c3/aop-c3.esp32.bin
