name: Compile Arduino sketch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Compile for Arduino Pro Mini
        working-directory: ./arduino
        run: |
          pio run -e pro -j3

      - name: Upload build-pro - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}-${{ env.repository_name }}-pro.avr.hex
          path: arduino/.pio/build/pro/firmware.hex

      - name: Compile for ESP32 C3
        working-directory: ./arduino
        run: |
          pio run -e esp32c3 -j3

      - name: Upload build-c3 - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}-${{ env.repository_name }}-c3.esp32.bin
          path: arduino/.pio/build/esp32c3/firmware.bin
